name: Build Cherif Send APK

on:
  push:
    branches:
      - transfert-local
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Donner les permissions à Gradle
        run: chmod +x android/gradlew

      - name: Compiler APK Debug
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Cherif-Send-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
